language: go

go:
  - 1.13.x

sudo: required

install:
  - go get -u github.com/magefile/mage
  - go get -u golang.org/x/lint/golint

script:
  - cp config.json.template config.json
  - mage -v install
  - mage -v check
