language: go

go:
  - 1.13.x

sudo: required

env:
  - CODECOV_TOKEN="68778948-28b1-47a7-adf2-2bb615eb5428"

install:
  - go get -u github.com/magefile/mage
  - go get -u golang.org/x/lint/golint

script:
  - cp config.json.template config.json
  - mage -v install
  - mage -v check

after_success:
  - bash <(curl -s https://codecov.io/bash)